---
abstract: 'Simple HTTP server for serving a CPAN mirror'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.42
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200001, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CPAN-Mirror-Server-HTTP
requires:
  File::Spec: 3.12
  Getopt::Long: 2.35
  HTML::Tiny: 1.05
  HTTP::Daemon: 5.827
  HTTP::Response: 0
  HTTP::Status: 0
  MIME::Base64: 3.07
  Number::Bytes::Human: 0.07
  Pod::Usage: 1.33
  perl: v5.8.8
resources:
  homepage: http://github.com/bingos/cpan-mirror-server-http/tree
  repository: git://github.com/bingos/cpan-mirror-server-http.git
version: 0.02
